export const GET_CURRENTUSER_SIGNUP = 'GET_CURRENTUSER_SIGNUP';
export const GET_CURRENTUSER_SIGNIN = 'GET_CURRENTUSER_SIGNIN';
export const CHECK_TOKEN = 'CHECK_TOKEN';
export const TOGGLE_LOGGED = 'TOGGLE_LOGGED';
export const GET_ROOMS = 'GET_ROOMS';
export const DISCONNECT = 'DISCONNECT';

export const OPEN_WEBSOCKET = 'OPEN_WEBSOCKET'
export const UPDATE_SOCKET_OBJECT = 'UPDATE_SOCKET_OBJECT';
export const SEND_USERNAME = 'SEND_USERNAME';
export const SEND_CONVERSATION = 'SEND_CONVERSATION';
export const SET_MESSAGES = 'SET_MESSAGES';
export const SET_TYPING = 'SET_TYPING';
export const SET_RECEIVER = 'SET_RECEIVER';